palantir_aliases:
  - &always-run
    filters:
      branches:
        only: /.*/
      tags:
        only: /.*/

version: 2.1


jobs:
  test:
    parameters:
      python_version:
        type: string
      pydantic_version:
        type: string
      httpx_version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python_version >>
    steps:
      - checkout
      - run: pip install --user tox
      - run: poetry --no-ansi install --no-root --sync
      - run: |
          PYDANTIC_VERSION=<< parameters.pydantic_version >>.* \
          HTTPX_VERSION=<< parameters.httpx_version >>.* \
          poetry --no-ansi run tox -v -e py<< parameters.python_version >> --recreate

  black:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: pip install --user tox
      - run: python -m tox -e black


  circle-all:
    docker:
      - image: node:lts
    steps:
      - run: echo "Done!"

  publish:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: python scripts/set_python_version.py
      - run: poetry version $(git describe --tags --abbrev=0)
      - run: poetry publish -v -u $PYPI_USERNAME -p $PYPI_PASSWORD --build

workflows:
  version: 2
  build:
    jobs:
      - test:
          <<: *always-run
          name: python-<< matrix.python_version>>
          matrix:
            parameters:
              python_version: ["3.9", "3.10", "3.11", "3.12"]
              pydantic_version: ["2.10"]
              httpx_version: ["0.28"]
      - test:
          <<: *always-run
          name: pydantic-<< matrix.pydantic_version >>
          matrix:
            parameters:
              python_version: ["3.12"]
              pydantic_version: ["2.6", "2.7", "2.8", "2.9", "2.10"]
              httpx_version: ["0.28"]
      - test:
          <<: *always-run
          name: httpx-<< matrix.httpx_version >>
          matrix:
            parameters:
              python_version: ["3.12"]
              pydantic_version: ["2.10"]
              httpx_version: ["0.25", "0.26", "0.27", "0.28"]
      - black:
          <<: *always-run
      - circle-all:
          <<: *always-run
          requires:
            - python-3.9
            - python-3.10
            - python-3.11
            - python-3.12

            - pydantic-2.6
            - pydantic-2.7
            - pydantic-2.8
            - pydantic-2.9
            - pydantic-2.10

            - httpx-0.25
            - httpx-0.26
            - httpx-0.27
            - httpx-0.28

            - black
      - publish:
          requires:
            - circle-all
          filters:
            tags: { only: '/^[0-9]+(\.[0-9]+)+(-[a-zA-Z]+[0-9]*)*$/' }
            branches: { ignore: /.*/ }
